triggers:
  - cron:
      spec: "*/1 * * * *"
      entryPoint: githubPRCleanup

flows:
  githubPRCleanup:
    - log: "Cleaning up existing pull requests created based on IMA testing"
    - set:
        githubToken: "${crypto.exportAsString('Hawkeye', 'github_token', null)}"
        secretValue: "${crypto.exportAsString('Hawkeye', 'hawkeye-kitt-pr-repos', null)}"
        products: "test-product,opc_ua_test,opc-ua-poc"
        githubProducts: [
          {productName: "test-product"},
          {productName: "opc_ua_test"},
          {productName: "opc-ua-poc"}]
        imaUserName: "amguist"
    - log: "Secret value is ${secretValue}"
    - expr: ${secretValue.flatMap(str -> str.split(",").stream()).toList()}
      out: productNames

  perform-cleanup:
    - set:
        projectName: ${item.productName}
    - log: "Cleaning up repository: ${projectName}"
    - expr: ${"https://github.com/".concat(organization).concat("/").concat(item.productName).concat(".git")}
      out: apiUrl
    - task: github
      in:
        action: getPRList
        accessToken: ${githubToken}
        org: ${organization}
        repo: ${item.productName}
        base: "main"
        state: "open"
    - if: ${prList.isEmpty()}
      then:
        - log: "No Open PRs to pull details for ..."
      else:
        - expr: ${prList.stream().filter(i -> i.user.login.equals(imaUserName) && i.head.ref.contains("-IMA")).map(c -> {'number':c.number,'branch':c.head.ref,'createTs':c.createdAt}).toList()}
          out: retrievedPullRequests
        - call: clean
          withItems: ${retrievedPullRequests}

  clean:
    - set:
        durationInMinutes: 0
